### ISSUE TITLE
Differences between different versions of the code

### ISSUE THREAD

**Issue by hadisfr** [xgfs/verse#18]
Hi!
In the [article](https://arxiv.org/pdf/1803.04742.pdf) it is said that multiple similarity functions, specifically PageRank, Adj., and SimRank, can be used.
In the codebase, except from recently-added weighted versions, there are three version of code with slight differences: `verse`, `verse-neigh`, and `verse-simrank`.
I don't get which one is which one. Can you please explain a little? 🤔  Are they PageRank, Adj., and SimRank, respectively?

**Comment by xgfs** [comment]
Yes, you are correct. Default is PageRank and adjacency is neighbor sampling.
