### ISSUE TITLE
question on node classification

### ISSUE THREAD

**Issue by jwijffels** [xgfs/verse#2]
I had a look at the paper of VERSE but can't understand what is done in case of node classification. 
Are the embeddings used using liblinear to do a binary yes/no classification or what is being used there?
Many thanks.

**Comment by xgfs** [comment]
Yes, essentially. VK classification is binary, Orkut is multi-class, and in YouTube labels overlap, so we use LabelPowerset from [scikit-multilearn](http://scikit.ml/). Let me know if you have any further clarifications.

**Comment by jwijffels** [comment]
Ok, thans. Clear now!
