### ISSUE TITLE
question on embeddings

### ISSUE THREAD

**Issue by jwijffels** [xgfs/verse#3]
I'm trying to find out what I can do with the embeddings. 
Would it make sense to build a graph where sentences are nodes and edges between these nodes exist if some words are overlapping and next use verse to obtain sentence embeddings? Or is this a stupid idea?

**Comment by xgfs** [comment]
Probably there are better methods for sentence classification that utilize more information about words, but graphs can be used effectively for unsupervised exploration. We outline an opportunity to use embeddings for clustering with simple k-means in the paper.

**Comment by jwijffels** [comment]
Ok. Thanks for the input.
