### ISSUE TITLE
question on input format

### ISSUE THREAD

**Issue by jwijffels** [xgfs/verse#4]
I'm seeing how to build an R wrapper around this. Can you explain a bit the BCSR format in words. What I'm trying to do is to understand what is in the offsets & edges c++ code you have there. Can you explain that in words so that I am 100% sure what they should be if I passed the data from R to C++

```
offsets = static_cast<int *>(aligned_malloc((nv + 1) * sizeof(int32_t), DEFAULT_ALIGN));
edges = static_cast<int *>(aligned_malloc(ne * sizeof(int32_t), DEFAULT_ALIGN));
embFile.read(reinterpret_cast<char *>(offsets), nv * sizeof(int32_t));
offsets[nv] = (int)ne;
embFile.read(reinterpret_cast<char *>(edges), sizeof(int32_t) * ne);
```

**Comment by xgfs** [comment]
I'd happily include/reference an R wrapper.

BCSR is essentially [CSR](https://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.sparse.csr_matrix.html) (python reference since I'm not an R user, but the standard is universal). If you have any (unweighted) graph in sparse matrix format, there should be a way to convert it to CSR. Then, 'indices' in the description of the format correspond to 'offsets' in the code, and 'edges' in the code correspond to 'indptr'.

**Comment by jwijffels** [comment]
Thank you for the input. I'll try to build an R wrapper around this.

**Comment by jwijffels** [comment]
Are you sure this is not CSC format which is implemented?

**Comment by xgfs** [comment]
> "Then, 'indices' in the description of the format correspond to 'edges' in the code, and 'offsets' in the code correspond to 'indptr'."

Yes, sorry.

**Comment by jwijffels** [comment]
Ok thanks for the confirmation.

**Comment by xgfs** [comment]
I will verify the correctness of the wrapper soon, and then would ask you to submit a pull request (or I do it myself), if you are not against it.

As for the inclusion, three programs only have a different Train() function, one can probably refactor the code to include three different cores, and the rest will be all the same.

**Comment by jwijffels** [comment]
Also these elements have the same name:
`rng_seed'
`sigmoid_table'
`nv'
`n_samples'
`w0'
`step'
`n_hidden'
`total_steps'
`offsets'
`edges'
`ppralpha'
`global_lr'
`silent'
`n_threads'
`n_epochs'
`ne'
`degrees'
I wonder how this should be refactored? Any idea?

**Comment by xgfs** [comment]
I mean, they could be shared, as their implementation is the same, and some logic inside the wrapper could raise a warning if the method is called twice, meaning the embeddings are not randomized.

**Comment by jwijffels** [comment]
Currently I only could include 1 of the 3 (verse.cpp) as including the other 2 give conflicts (shown above). This might need some refactoring if I would like to also include verse, deepwalk and node2vec in the same R package.

**Comment by xgfs** [comment]
I'm currently re-writing the code for DeepWalk, n2v and Verse to allow for such library.
Please wait a little bit, as the architecture will change a little (i.e. allocations are managed by the Python/R code).

**Comment by xgfs** [comment]
The reasoning is essentially since it's a research work, people must be able to reproduce it, including the scalability. If I outsource some parts to Python, I'll inevitably lose some speed due to different memory layouts. Code as is is extremely inflexible t obe used as a library.

**Comment by jwijffels** [comment]
Yes, I understand. Maybe this can be rewritten with classes or templates in order to allow more easily to be used by python/R? For what it is worth, the code which I written to wrap it looks like this: https://www.datatailor.be/open-source/deepwalker/blob/master/src/verse.cpp
