### ISSUE TITLE
Weight type in converter

### ISSUE THREAD

**Issue by iggisv9t** [xgfs/verse#6]
In readme example for weighted_edgelist, weights are float. I get `AssertionError: negative weights are not allowed` when converted my graph to bcsr, but there was only positive weights. In converter.py weights are converted to `np.int32`, so problem that I get type overflow when converted large float64 to int32. I think you should ether change the conversion pipeline or change example to integer weights and add assertion.

**Comment by xgfs** [comment]
Changed the weight type to float32. Should work now.
I'm not sure how that was working before :)
