### ISSUE TITLE
why not use c

### ISSUE THREAD

**Issue by dywlegend** [xgfs/verse#8]
Hi Authors,

I have a question. why not use c to complete converting raw dara to binary csr matrix? 

For large amounts of data, using Python makes me waste too much time. 

Hope that helps.

dywlegend

**Comment by xgfs** [comment]
If the data is already in a matrix format, converting should not be an issue of Python. Otherwise, there is too much flexibility in common formats to rewrite them all to C. If you want to do this, I will gladly include the converter.
